import gameData from '../content/game-data.json';
export type Language = 'zh-TW' | 'en' | 'ja';
const contentText: Record<string, string[]> = gameData.texts;
const text: Record<string, [string, string, string]> = {
  ground: ['地面聚落', 'Ground settlement', '地上集落'], overview: ['聚落', 'Settlement', '集落'], species: ['物種', 'Species', '種族'], workers: ['工作派遣', 'Assignments', '作業割り当て'], buildings: ['建設', 'Construction', '建設'], science: ['研究', 'Research', '研究'], records: ['紀錄', 'Records', '記録'], achievements: ['成就', 'Achievements', '実績'], legacy: ['傳承', 'Legacy', '継承'], settings: ['設定與存檔', 'Settings & save', '設定とセーブ'],
  wood: ['木頭', 'Wood', '木材'], stone: ['石頭', 'Stone', '石材'], food: ['食物', 'Food', '食料'], planks: ['木板', 'Planks', '板材'], knowledge: ['知識', 'Knowledge', '知識'],
  base: ['未分化分支', 'Undifferentiated branch', '未分化分岐'], forest: ['林地型', 'Woodland form', '森林型'], symbiosis: ['共生型', 'Symbiotic form', '共生型'], mineral: ['礦質分支', 'Mineral branch', '鉱物分岐'],
  workwood: ['伐木', 'Woodcutting', '伐採'], workstone: ['採石', 'Mining', '採石'], workfood: ['採集食物', 'Foraging', '食料採集'], workbuild: ['建造', 'Building', '建設'], workcraft: ['加工', 'Crafting', '加工'], workresearch: ['研究', 'Research', '研究'],
  habitat: ['礦質棲地', 'Mineral habitat', '鉱物分岐の居住地'], lumberyard: ['伐木設施', 'Lumberyard', '伐採施設'], warehouse: ['倉庫', 'Warehouse', '倉庫'], laboratory: ['研究站', 'Research station', '研究所'], workshop: ['工坊', 'Workshop', '工房'], monument: ['文明傳承碑', 'Legacy monument', '文明継承碑'], expansion1: ['聚落擴建 I', 'Settlement expansion I', '集落拡張 I'], expansion2: ['聚落擴建 II', 'Settlement expansion II', '集落拡張 II'], camp: ['營地擴充', 'Camp extension', '拠点拡張'], mineralHabitat: ['第二礦質棲地', 'Second mineral habitat', '第2鉱物居住地'], recruit: ['招募基礎單位', 'Recruit a base worker', '基本ユニットの募集'], crafting: ['工藝研究', 'Crafting research', '工芸研究'], planning: ['聚落規劃', 'Settlement planning', '集落計画'],
  habitatDesc: ['礦質棲地 +2, 開放物種分歧', '+2 mineral habitat spaces, unlocks evolution', '鉱物分岐の居住枠 +2、種族進化を解放'],
  lumberyardDesc: ['2 名伐木者產率 +20%, 每隻限一次加成', '+20% output for 2 woodcutters, once per worker', '伐採者2体の生産量 +20%、各ユニットに1回まで'],
  warehouseDesc: ['所有資源容量 +800', '+800 capacity per resource', '全資源の容量 +800'],
  laboratoryDesc: ['研究名額 +2, 基礎產率每隻 0.25 知識 / 秒', '+2 research slots, base 0.25 knowledge / worker / s', '研究枠 +2、基本生産量は1体あたり毎秒0.25知識'],
  workshopDesc: ['加工名額 +1, 建造佇列 +1, 每木板消耗 5 木頭', '+1 crafting slot, +1 queue slot, 5 wood / plank', '加工枠 +1、建設キュー +1、板材1枚に木材5を消費'],
  monumentDesc: ['開放傳承, 本輪收益 +10', 'Unlocks Reset, +10 legacy this run', '継承を解放、今回の報酬 +10'],
  expansion1Desc: ['本輪傳承收益增加 5', 'Adds 5 legacy to this run', '今回の継承報酬 +5'], expansion2Desc: ['本輪傳承收益再增加 5', 'Adds another 5 legacy to this run', '今回の継承報酬をさらに +5'],
  campDesc: ['基礎棲地 +2', '+2 base habitat spaces', '基本種族の居住枠 +2'], mineralHabitatDesc: ['礦質棲地 +2', '+2 mineral habitat spaces', '鉱物分岐の居住枠 +2'], recruitDesc: ['新增 1 個基礎單位, 需營地空位', 'Adds 1 base worker; requires a free camp space', '基本ユニット1体を追加、拠点の空き枠が必要'],
  craftingDesc: ['解鎖工坊與木板產線', 'Unlocks the workshop and plank production', '工房と板材生産を解放'], planningDesc: ['解鎖文明傳承碑, 建造佇列容量 +2', 'Unlocks the legacy monument and adds 2 construction queue slots', '文明継承碑を解放、建設キューの容量 +2'],
  tools: ['基礎工具', 'Basic tools', '基本工具'], startChoice: ['起始型態選擇', 'Starting form choice', '初期形態の選択'], templates: ['工作配置模板', 'Work templates', '作業配置テンプレート'],
  toolsDesc: ['每級伐木與採石 +5%, 最多 5 級', '+5% wood and stone per level, up to 5 levels', 'レベルごとに伐採と採石 +5%、最大5レベル'], startChoiceDesc: ['新一輪可從已發現型態起步', 'Start a new run in a discovered form', '発見済みの形態で次の周回を開始'], templatesDesc: ['儲存並手動套用配置, 新到的單位可補入空位', 'Save and apply a work plan; new arrivals can fill available slots', '配置を保存して手動で適用、新規ユニットで空き枠を補充'],
  population: ['物種總數', 'Workers', 'ユニット総数'], run: ['第 {n} 輪', 'Run {n}', '第{n}周'],
  branchTitle: ['物種分歧', 'Species evolution', '種族進化'], branchHelp: ['每輪限選一次', 'One choice per run', '各周回で1回のみ選択'],
  forestDesc: ['伐木適性 +50%', '+50% woodcutting aptitude', '伐採適性 +50%'], symbiosisDesc: ['採集食物適性 +50%', '+50% foraging aptitude', '食料採集適性 +50%'], choose: ['選擇', 'Choose', '選択'],
  status: ['生產狀態', 'Production status', '生産状況'],
  foodBalance: ['採集食物 {made} / 秒, 維持需求 {need} / 秒', 'Foraging {made} / s, upkeep {need} / s', '食料採集 {made} / 秒、維持費 {need} / 秒'],
  build: ['建造', 'Build', '建設'], paused: ['已暫停', 'Paused', '一時停止中'], pause: ['暫停', 'Pause', '一時停止'], resume: ['繼續', 'Resume', '再開'], cancel: ['取消並返還材料', 'Cancel & return materials', '中止して資材を返却'], activeBuild: ['正在建造', 'Construction in progress', '建設中'], waitingBuild: ['尚未開工', 'No active construction', '未着工'], noBuilders: ['缺少建造者, 請到工作派遣指派', 'No builders; assign them in Assignments', '建設担当が不足、作業割り当てで設定してください'], workUnit: ['工作量', 'work', '作業量'], remaining: ['預估剩餘', 'Estimated remaining', '残り時間の目安'],
  busy: ['已有建造項目', 'Construction slot occupied', '建設中の項目あり'], locked: ['尚未解鎖', 'Locked', '未解放'], completed: ['已完成', 'Completed', '完了'], materials: ['材料不足', 'Not enough resources', '資源不足'], habitatFull: ['棲地已滿', 'Habitat full', '居住枠が満員'],
  requirement: ['需要: {item}', 'Requires: {item}', '必要: {item}'], progress: ['進度', 'Progress', '進捗'],
  refundTitle: ['待領回材料', 'Reserved materials', '返却待ちの資材'], refundHelp: ['返還時超出儲存容量的材料會保留在此, 騰出空間後即可領回', 'Refunds beyond capacity stay here. Claim them after making room.', '容量を超えた返却資材はここに保管されます。空きを作ると受け取れます。'], claim: ['領回材料', 'Claim resources', '資材を受け取る'],
  idle: ['閒置', 'Idle', '待機'], baseUpkeep: ['每隻消耗 0.05 食物 / 秒, 含閒置', '0.05 food / worker / s, including idle', '待機中も含め、1体あたり毎秒0.05食料を消費'], mineralUpkeep: ['不消耗食物, 較耐惡劣天氣', 'No food upkeep, weather resistant', '食料消費なし、悪天候に強い'],
  addWorker: ['增加 {species} 的 {job} 數量', 'Add a {species} worker to {job}', '{species}の{job}担当を増やす'], removeWorker: ['減少 {species} 的 {job} 數量', 'Remove a {species} worker from {job}', '{species}の{job}担当を減らす'], unsupported: ['不支援此工作', 'Work not supported', 'この作業には対応していません'], slotsFull: ['工作名額已滿', 'Work slots full', '作業枠が満員'], workersError: ['沒有可用單位', 'No available worker', '割り当て可能なユニットなし'], invalidAssignment: ['指派數量不合法', 'Invalid assignment', '割り当て数が不正です'], noTask: ['沒有建造項目', 'No construction project', '建設項目なし'],
  efficiency: ['適性', 'Aptitude', '適性'], slots: ['名額', 'Slots', '枠'], noMinerals: ['完成礦質棲地後加入第二物種', 'Complete a mineral habitat to recruit your second species', '鉱物分岐の居住地を完成すると第2つの分岐を追加できます'],
  purchase: ['研究', 'Research', '研究'],
  legacyPoints: ['傳承點數', 'Legacy points', '継承ポイント'], resetCount: ['已完成輪次', 'Completed cycles', '完了した周回'], availableReward: ['本輪可領', 'Run reward', '今回の報酬'], reset: ['領取傳承並重開', 'Claim & restart', '継承を受け取って再開始'], abandon: ['放棄本輪', 'Abandon run', '今回の周回を放棄'], resetHelp: ['清除本輪資源, 物種, 派遣, 建築, 研究與分歧, 保留傳承點數與升級, 成就, 已發現型態, 工作模板及星球時間', 'Clears run resources, workers, assignments, buildings, research and evolution. Keeps legacy points and upgrades, achievements, discovered forms, work plans and planet time.', '今回の資源、種族、配置、建築、研究、進化をリセットします。継承ポイントと強化、実績、発見済み形態、作業テンプレート、惑星の時間は維持されます。'],
  resetConfirm: ['確認開啟新一輪', 'Confirm Reset', '次の周回を開始しますか'], abandonConfirm: ['確認放棄本輪', 'Confirm abandoning this run', '今回の周回を放棄しますか'], abandonHelp: ['本次收益為 0, 清除剩餘加速時間, 保留已有傳承與升級, 重開地面營地', 'This gives 0 reward and clears remaining acceleration time. Existing legacy and upgrades are kept; restart at the ground camp.', '今回の報酬は0です。残りの加速時間を消去し、既存の継承と強化を維持して地上拠点を再開始します。'], confirm: ['確認', 'Confirm', '確認'], dismiss: ['關閉', 'Dismiss', '閉じる'], newForm: ['下一輪起始型態', 'Next starting form', '次の周回の初期形態'], buy: ['購買升級', 'Buy upgrade', '強化を購入'], level: ['等級 {n} / 5', 'Level {n} / 5', 'レベル {n} / 5'], legacyPointsError: ['傳承不足', 'Not enough legacy', '継承ポイント不足'],
  saveTemplate: ['儲存目前配置', 'Save current plan', '現在の配置を保存'], applyTemplate: ['套用配置', 'Apply plan', '配置を適用'], noTemplate: ['尚未儲存配置', 'No saved plan', '保存済みの配置なし'],
  language: ['語言', 'Language', '言語'],
  recordFilter: ['紀錄分類', 'Record category', '記録の分類'], recordall: ['全部', 'All', 'すべて'], recordconstruction: ['建造', 'Construction', '建設'], recordresearch: ['研究', 'Research', '研究'], recordpopulation: ['物種', 'Species', '種族'], recordprogress: ['發展', 'Progress', '発展'],
  appearance: ['明暗模式', 'Appearance', '表示モード'], systemAppearance: ['跟隨系統', 'System', 'システムに合わせる'], lightAppearance: ['明色', 'Light', 'ライト'], darkAppearance: ['暗色', 'Dark', 'ダーク'],
  theme: ['主題', 'Theme', 'テーマ'], themeSand: ['砂墨暖調', 'Warm Sand & Ink', '砂墨暖調'], themeWorkbench: ['蒼藍夜幕', 'Azure Nightfall', '蒼藍夜幕'], mainNavigation: ['主選單', 'Main navigation', 'メインメニュー'], originalArtwork: ['圖示與星神紋章為本遊戲原創', 'Icons and deity emblems are original artwork for this game.', 'アイコンと星神の紋章は本作オリジナルです。'], starved: ['一隻單位死亡', 'One unit died', 'ユニット1体が死亡'], planetSpecies: ['聚落物種', 'Colony species', '集落の種族'],
  saveTitle: ['存檔與載入', 'Save & load', '保存と読込'], save: ['立即存檔', 'Save now', '今すぐセーブ'], export: ['匯出存檔', 'Export save', 'セーブをエクスポート'], import: ['匯入存檔', 'Import save', 'セーブをインポート'], importHelp: ['選擇檔案或貼上存檔, 匯入會取代目前進度, 請先匯出備份', 'Choose a file or paste a save. Import replaces current progress; export a backup first.', 'ファイルを選択するかセーブを貼り付けてください。現在の進行状況を置き換えるため、先にバックアップをエクスポートしてください。'],
  importConfirm: ['匯入並取代進度', 'Import & replace', 'インポートして置き換える'], recoverBackup: ['還原上一份存檔', 'Restore previous save', '前のセーブを復元'], exportRaw: ['匯出原始存檔', 'Export original save', '元のセーブをエクスポート'], jsonLabel: ['存檔內容', 'Save contents', 'セーブ内容'], saved: ['已儲存', 'Saved', '保存済み'], notSaved: ['尚未儲存', 'Not saved yet', '未保存'],
  savingHelp: ['自動儲存於此瀏覽器, 換裝置前請匯出備份', 'Auto-saved in this browser. Export a backup before switching devices.', 'このブラウザへ自動保存します。端末を変更する前にバックアップをエクスポートしてください。'],
  imported: ['存檔已匯入', 'Save imported', 'セーブをインポートしました'], invalidSave: ['存檔不合法, 原進度已保留', 'Invalid save; existing progress is preserved', 'セーブが不正です。現在の進行状況は維持されています。'], unsupportedSave: ['不支援此存檔版本, 原進度已保留', 'Unsupported save version; existing progress is preserved', '対応していないセーブ形式です。現在の進行状況は維持されています。'], storageError: ['瀏覽器儲存失敗; 請匯出進度; 新一輪尚未成功儲存時不會入帳', 'Browser storage failed. Export your progress. An unsaved Reset is not credited.', 'ブラウザへの保存に失敗しました。進行状況をエクスポートしてください。次の周回の保存が完了するまで、継承報酬は確定しません。'],
  damagedSave: ['原存檔無法讀取, 已停止自動覆寫; 請匯出原檔, 還原備份或匯入有效存檔', 'Save unreadable; automatic overwrites stopped. Export the original, restore a backup or import a valid save.', '元のセーブを読み込めず、自動上書きを停止しました。元データをエクスポートし、バックアップを復元するか有効なセーブをインポートしてください。'], backupRecovered: ['已從備份恢復, 請檢查進度並匯出備份', 'Recovered from backup. Check progress and export a backup.', 'バックアップから復元しました。進行状況を確認し、バックアップをエクスポートしてください。'], noBackup: ['沒有可用備份', 'No backup available', '利用可能なバックアップなし'],
  inactiveTab: ['此分頁待接續', 'Inactive tab', 'このタブは待機中'], browserUnsupported: ['此瀏覽器無法啟動遊戲; 請使用新版 Edge, Chrome, Firefox 或 Safari', 'This browser cannot start the game. Use a current Edge, Chrome, Firefox or Safari.', 'このブラウザでは起動できません。新しいEdge、Chrome、Firefox、Safariを使用してください。'], sessionError: ['遊戲無法載入, 請備份原存檔後重新整理', 'The game could not load. Back up the original save before reloading.', 'ゲームを読み込めませんでした。元のセーブをバックアップしてから再読み込みしてください。'], simulationError: ['遊戲已暫停, 請匯出存檔並回報問題', 'The game has paused. Export your save and report the issue.', 'ゲームを一時停止しました。セーブをエクスポートして問題を報告してください。'], clockBackwards: ['裝置時間早於存檔時間, 本次沒有離線收益', 'Your device clock is earlier than the save time. No offline progress was added.', '端末の時刻がセーブ時刻より前のため、今回は加速時間を追加していません。'],
  bankHelp: ['離開 1.5 小時累積 1 小時的 2 倍加速時間, 最多 8 小時, 遊玩時自動使用, 暫停時停止累積與使用', 'Every 1.5 hours away grants 1 hour of double-speed play, up to 8 hours. It is used automatically while playing. Pausing stops earning and using it.', '離れていた時間1.5時間につき、2倍速の加速時間を1時間蓄積します。上限は8時間で、プレイ中に自動使用します。一時停止中は蓄積と使用を停止します。'],
  accelerationRemaining: ['剩餘 {n} 分鐘', '{n} minutes remaining', '残り{n}分'],
  nativeCivilization: ['原生文明', 'Native civilization', '原生文明'], nativeIntelligence: ['原生智慧物種', 'Native intelligent species', '原生知的種族'], civilizationDevelopment: ['文明發展', 'Civilization development', '文明の発展'],
  nativehumanoid: ['類人族', 'Humanoid species', '人型種族'], nativecarapace: ['甲殼族', 'Carapace species', '甲殻種族'], nativecrystalline: ['晶質族', 'Crystalline species', '結晶種族'], nativemycelial: ['菌絲族', 'Mycelial species', '菌糸種族'],
  developmentsettlements: ['聚落社會', 'Settlement society', '集落社会'], developmentcityStates: ['城邦社會', 'City-state society', '都市国家社会'], developmentindustrial: ['工業社會', 'Industrial society', '産業社会'],
  buildingQueued: ['已排入佇列', 'Already queued', 'キューに登録済み'],
  offlineHelp: ['遊戲資料下載完成後可無網路開啟, 更新會在關閉所有遊戲分頁後啟用, 清除網站資料會移除本機存檔', 'Once game files have downloaded, you can open the game offline. Updates take effect after all game tabs close. Clearing site data removes local saves.', 'ゲームデータのダウンロード後はオフラインで起動できます。更新は全ゲームタブを閉じると有効になります。サイトデータを削除すると、端末内のセーブも削除されます。'],
  region: ['區域', 'Region', '地域'], regionhome: ['起始平原', 'Starting plains', '初期平原'], regionupland: ['高地', 'Uplands', '高地'], regioncoast: ['沿岸', 'Coast', '沿岸'],
  regionHelp: ['聚落位於起始平原', 'Your settlement is in the starting plains.', '集落は初期平原にあります'],
  journal: ['聚落紀錄', 'Settlement journal', '集落の記録'], arrival: ['工作隊抵達地面營地', 'Your workers arrived at the ground camp', '作業隊が地上拠点に到着'], started: ['開始建造 {item}', 'Started {item}', '{item}の建設を開始'], built: ['完成 {item}', 'Completed {item}', '{item}が完成'], cancelled: ['取消 {item}, 材料已退還或保留', 'Cancelled {item}; resources refunded or reserved', '{item}を中止、資材は返却または保管済み'], evolved: ['基礎物種分歧為 {item}', 'Base species evolved into {item}', '基本種族が{item}に進化'], researched: ['完成 {item}', 'Researched {item}', '{item}の研究が完了'], purchased: ['購入 {item}', 'Purchased {item}', '{item}を購入'], resetDone: ['文明傳承已入帳, 新一輪開始', 'Legacy credited. A new run begins.', '継承を獲得し、次の周回を開始'],
  full: ['滿倉', 'Full', '容量上限'], unavailable: ['待解鎖', 'Locked', '未解放'], craftBlocked: ['加工受木頭供給或木板容量限制', 'Crafting limited by wood supply or plank capacity', '木材の供給または板材の容量により加工を制限'], noCraftWorkers: ['工坊需要 1 名加工者', 'The workshop needs a crafter', '工房には加工担当1体が必要'],
  newSettlement: ['重新建立聚落', 'Restart settlement', '集落を再開始'],
  version: ['版本', 'Version', 'バージョン'], showCompleted: ['顯示已達上限', 'Show maxed', '上限に達した項目を表示'], noAvailableBuildings: ['目前沒有可建造的項目', 'No construction available', '現在建設可能な項目なし'], resourcesTitle: ['資源', 'Resources', '資源'], colonySummary: ['聚落總覽', 'Colony overview', '集落の概要'],
  populationCount: ['{n} / {max} 隻', '{n} / {max} units', '{n} / {max}体'], spawn: ['生成 1 隻', 'Generate 1', '1体生成'], spawned: ['生成 1 隻 {item}', 'Generated 1 {item}', '{item}を1体生成'],
  planetTitle: ['星球環境', 'Planet environment', '惑星環境'], universeTitle: ['宇宙', 'Universe', '宇宙'], universestandard: ['常態宇宙', 'Standard universe', '標準宇宙'], universedense: ['高重力宇宙', 'Dense universe', '高重力宇宙'], universevolatile: ['動盪宇宙', 'Volatile universe', '不安定宇宙'], planetName: ['星球', 'Planet', '惑星'], planetDesignation: ['星球 {n}', 'Planet {n}', '惑星 {n}'], rotation: ['自轉週期', 'Rotation period', '自転周期'], orbit: ['公轉週期', 'Orbital period', '公転周期'], planetDays: ['{n} 個當地日', '{n} local days', '現地の{n}日'], season: ['季節', 'Season', '季節'], weather: ['天氣', 'Weather', '天候'], spring: ['春季', 'Spring', '春'], summer: ['夏季', 'Summer', '夏'], autumn: ['秋季', 'Autumn', '秋'], winter: ['冬季', 'Winter', '冬'], clear: ['晴朗', 'Clear', '晴れ'], rain: ['降雨', 'Rain', '雨'], drought: ['乾旱', 'Drought', '干ばつ'], storm: ['暴風雨', 'Storm', '嵐'], frost: ['寒流', 'Cold snap', '寒波'], daylight: ['白天', 'Day', '昼'], night: ['夜晚', 'Night', '夜'], calendarDay: ['第 {year} 年 / 第 {day} 日', 'Year {year} / day {day}', '{year}年 / {day}日'],
  outdoorModifiers: ['基礎物種環境倍率', 'Base species environment', '基本種族の環境倍率'], shelteredWork: ['研究與加工不受天氣影響', 'Research and crafting are sheltered', '研究と加工は天候の影響を受けません'],
  achievementCount: ['已達成 {n} / {max}', '{n} / {max} earned', '達成 {n} / {max}'], noPermanentBonuses: ['達成成就後自動取得永久加成', 'Earn achievements to gain permanent bonuses', '実績を達成すると永続ボーナスを獲得'], earned: ['已達成', 'Earned', '達成済み'], unearned: ['未達成', 'Not earned', '未達成'], achievementPending: ['尚未達成條件', 'Conditions not yet met', '条件未達成'], seconds: ['秒', 'seconds', '秒'], earnedAt: ['達成時間: {time}', 'Earned: {time}', '達成日時: {time}'], achievementUnlocked: ['成就達成: {item}', 'Achievement earned: {item}', '実績達成: {item}'],
  achievementsettlement: ['落地生根', 'First foundation', '最初の礎'], achievementsettlementDesc: ['完成第一座礦質棲地', 'Complete the first mineral habitat', '最初の鉱物分岐の居住地を完成'], achievementdiversity: ['各展所長', 'Many strengths', '多様な才能'], achievementdiversityDesc: ['生成礦質分支, 聚落擁有兩種分支', 'Generate a mineral branch to house two branches', '鉱物分岐を生成し、集落に2つの分岐を揃える'], achievementscholar: ['知識之路', 'Path of knowledge', '知識への道'], achievementscholarDesc: ['完成第一項研究', 'Complete your first research', '最初の研究を完了'], achievementlegacy: ['文明延續', 'Civilization endures', '文明の継続'], achievementlegacyDesc: ['完成一次傳承並開啟新一輪', 'Claim legacy and begin a new cycle', '継承を受け取り、次の周回を開始'], achievementendurance: ['風雨同舟', 'Weathering the storm', '嵐を越えて'], achievementenduranceDesc: ['派遣單位在暴風雨或寒流期間累計工作 300 秒', 'Keep workers assigned through storms or cold snaps for 300 seconds', '嵐または寒波の間に、割り当てたユニットが累計300秒作業する'],
  exportBeforeUpgrade: ['匯出升級前存檔', 'Export pre-upgrade save', '更新前のセーブをエクスポート'],
  online: ['運作中', 'Running', '稼働中'], loading: ['正在載入營地', 'Loading your camp', '拠点を読み込み中'], allocation: ['{used} / {total} 已指派', '{used} / {total} assigned', '{used} / {total}体を配置'],
  gameSettings: ['遊戲設定', 'Game settings', 'ゲーム設定'],
  iconCredits: ['圖示', 'Icons', 'アイコン'],
  about: ['關於', 'About', 'このゲームについて'],
  starGods: ['星神', 'Star deities', '星神'], starGodConfirm: ['確認選擇星神', 'Confirm deity choice', '星神を選択しますか'], starGodHelp: ['每輪手動選一位, 本輪不能更換, 重開時清除', 'Choose one each run. The choice lasts until the next restart.', '各周回で1柱を選択。この周回では変更できず、再開始時に解除されます。'], starGodLocked: ['本輪已選定星神', 'A deity is already chosen for this run', 'この周回の星神は選択済みです'], invalidStarGod: ['無法選擇此星神', 'This deity cannot be selected', 'この星神は選択できません'], starGodChosen: ['已選擇 {item}', 'Chose {item}', '{item}を選択'],
  queueCapacityHelp: ['初始 2 個名額, 包含正在建造的項目; 每座工坊 +1, 聚落規劃 +2, 最多 12 個', 'Starts with 2 slots including active construction; each workshop adds 1 and settlement planning adds 2, up to 12', '初期は建設中も含め2枠。工房ごとに+1、集落計画で+2、最大12枠。'], queueTimeHelp: ['依目前建造效率估算的施工時間, 等候材料及前項工程的時間另計', 'Construction time at current efficiency; excludes waiting for materials and earlier projects', '現在の建設効率による所要時間。資材や前の工事の待ち時間は含みません。'],
  queueDragHelp: ['拖曳建築名稱調整等候順序; 鍵盤可用 Alt + 上下方向鍵', 'Drag a building name to reorder waiting projects; use Alt + Up or Down with a keyboard', '建築名をドラッグして順番を変更。キーボードではAlt + 上下矢印キーを使用。'], queueDrag: ['拖曳排序 {item}', 'Drag to reorder {item}', '{item}をドラッグして並べ替え'],
  subtabs: ['內容分類', 'Content sections', '内容の分類'], summary: ['總覽', 'Overview', '概要'], environmentDetails: ['環境詳情', 'Environment details', '環境の詳細'], availableResearch: ['可研究科技', 'Available technologies', '研究可能な技術'], completedResearch: ['已完成研究', 'Completed research', '完了した研究'], milestoneTab: ['發展進度', 'Milestones', '発展状況'], journalTab: ['聚落紀錄', 'Journal', '集落の記録'], achievementList: ['成就列表', 'Achievements', '実績一覧'], permanentBonuses: ['永久加成', 'Permanent bonuses', '永続ボーナス'], legacyOverview: ['文明傳承', 'Civilization legacy', '文明の継承'],
  buildingCount: ['已建 {n} 座', '{n} built', '建設済み {n}棟'], uniqueBuilding: ['限建 1 座', 'Limit 1', '1棟まで'], plannedCount: ['已排入 {n} 座', '{n} planned', 'キュー登録済み {n}棟'], buildingLimit: ['已達建造上限', 'Building limit reached', '建設上限に到達'], addToQueue: ['排入佇列', 'Queue', 'キューに追加'], queueFull: ['建造佇列已滿', 'Queue full', '建設キューが満杯'], invalidQueue: ['此建造項目已變動', 'This queue entry has changed', 'この建設項目は変更されています'], buildQueue: ['建造佇列', 'Construction queue', '建設キュー'], queuePaused: ['佇列已暫停, 正在建造的項目會繼續', 'Queue paused; active construction continues', 'キューは一時停止中、建設中の項目は継続'], queueWaiting: ['依序接續, 開工時消耗材料', 'Continues in order; materials are consumed at start', '順番に着工し、着工時に資材を消費'], queueNeedsMaterials: ['等待材料足夠後自動開工', 'Starts automatically when materials are ready', '資材が揃うと自動で着工'], queueNeedsStorage: ['材料需求超出容量, 請先擴充倉庫', 'Cost exceeds capacity; expand storage first', '必要資材が容量を超えています。先に倉庫を拡張してください。'], pauseQueue: ['暫停佇列', 'Pause queue', 'キューを一時停止'], resumeQueue: ['繼續佇列', 'Resume queue', 'キューを再開'], queueMoveUp: ['將 {item} 往前移', 'Move {item} earlier', '{item}の順番を前へ'], queueMoveDown: ['將 {item} 往後移', 'Move {item} later', '{item}の順番を後ろへ'], queueRemove: ['移除 {item}', 'Remove {item}', '{item}を削除'], queued: ['{item} 已加入建造佇列', '{item} added to construction queue', '{item}を建設キューに追加'], queueRemoved: ['{item} 已從建造佇列移除', '{item} removed from construction queue', '{item}を建設キューから削除'],
  forestry: ['林地經營', 'Woodland management', '森林管理'], forestryDesc: ['伐木產率 +10%, 解鎖培育林地', '+10% wood output, unlocks cultivated groves', '伐採生産量 +10%、育成林を解放'], cultivation: ['生態栽培', 'Ecological cultivation', '生態栽培'], cultivationDesc: ['採集食物產率 +10%, 開放生命調和研究', '+10% food output, unlocks vitality research', '食料採集の生産量 +10%、生命調和の研究を解放'], mineralogy: ['礦質共振', 'Mineral resonance', '鉱物共振'], mineralogyDesc: ['礦質分支採石產率 +15%, 解鎖共振採石場', '+15% mineral-branch stone output, unlocks resonance quarries', '鉱物分岐の採石生産量 +15%、共振採石場を解放'], arcana: ['魔力運用', 'Arcane application', '魔力利用'], arcanaDesc: ['魔法之風提升研究產率, 解鎖魔力共鳴塔', 'Magic winds improve research output, unlocks resonators', '魔力の風で研究生産量を向上、魔力共鳴塔を解放'], vitality: ['生命調和', 'Vital harmonization', '生命調和'], vitalityDesc: ['戶外採集與建造效率 +8%', '+8% outdoor gathering and construction', '屋外採集と建設の効率 +8%'],
  grove: ['培育林地', 'Cultivated grove', '育成林'], groveDesc: ['伐木產率 +5%', '+5% wood output', '伐採生産量 +5%'], quarry: ['共振採石場', 'Resonance quarry', '共振採石場'], quarryDesc: ['礦質分支採石產率 +5%', '+5% mineral-branch stone output', '鉱物分岐の採石生産量 +5%'], resonator: ['魔力共鳴塔', 'Arcane resonator', '魔力共鳴塔'], resonatorDesc: ['提升魔力研究增益, 隨星球魔力與物種親和性變動', 'Boosts arcane research by planet magic and species affinity', '研究への魔力ボーナスを強化、惑星の魔力と種族の親和性に応じて変化'],
  mineralCondition: ['礦質分支至少 {n} 隻', 'At least {n} mineral workers', '鉱物分岐が{n}体以上'], moistureCondition: ['水分係數至少 {n}%', 'Moisture at least {n}%', '水分係数{n}%以上'], arcaneCondition: ['魔力潛能至少 {n}%', 'Arcane potential at least {n}%', '魔力潜在力{n}%以上'], vitalityCondition: ['生命脈動至少 {n}%', 'Vitality field at least {n}%', '生命の脈動{n}%以上'], noCompletedResearch: ['尚未完成研究', 'No completed research', '完了した研究なし'], noAvailableResearch: ['目前沒有新的可研究科技', 'No new technologies available', '新たに研究可能な技術なし'],
  gravity: ['相對重力', 'Relative gravity', '相対重力'], moisture: ['水分係數', 'Moisture', '水分係数'], arcanePotential: ['魔力潛能', 'Arcane potential', '魔力潜在力'], vitalityField: ['生命脈動', 'Vitality field', '生命の脈動'], magicWind: ['魔法之風', 'Magic winds', '魔力の風'], magicWindPulse: ['魔力潮汐', 'Arcane tide', '魔力の潮汐'], magicAffinity: ['魔力親和性', 'Magic affinity', '魔力親和性'], vitalityAffinity: ['生命親和性', 'Vitality affinity', '生命親和性'],
  bonussettlement: ['永久加成: 建造效率 +2%', 'Permanent: +2% construction', '永続: 建設効率 +2%'], bonusdiversity: ['永久加成: 採石產率 +2%', 'Permanent: +2% stone output', '永続: 採石生産量 +2%'], bonusscholar: ['永久加成: 研究產率 +3%', 'Permanent: +3% research output', '永続: 研究生産量 +3%'], bonuslegacy: ['永久加成: 伐木, 採石與採集食物產率 +2%', 'Permanent: +2% wood, stone and food output', '永続: 伐採、採石、食料採集の生産量 +2%'], bonusendurance: ['永久加成: 天氣造成的效率損失減少 10%', 'Permanent: weather efficiency losses reduced by 10%', '永続: 天候による効率低下を10%軽減'], earnedDateUnknown: ['舊存檔未記錄達成日期', 'Earned date was not recorded in the older save', '旧セーブには達成日時の記録がありません'], compressionUnsupported: ['此瀏覽器無法解壓縮存檔, 請使用新版瀏覽器或匯入原始存檔', 'This browser cannot decompress saves. Use a current browser or import the original save', 'このブラウザではセーブを展開できません。新しいブラウザを使うか元のセーブをインポートしてください。'],
};
export function translate(language: Language, key: string, values: Record<string, string | number> = {}): string {
  let result = (contentText[key] ?? text[key])?.[language === 'zh-TW' ? 0 : language === 'en' ? 1 : 2] ?? key;
  for (const [name, value] of Object.entries(values)) result = result.replaceAll(`{${name}}`, String(value));
  return result;
}
export function duration(seconds: number): string {
  if (!Number.isFinite(seconds)) return '--:--';
  const value = Math.max(0, Math.ceil(seconds));
  const hours = Math.floor(value / 3600);
  const minutes = Math.floor(value % 3600 / 60);
  const secs = (value % 60).toString().padStart(2, '0');
  return hours ? `${hours}:${minutes.toString().padStart(2, '0')}:${secs}` : `${minutes}:${secs}`;
}
