import gameData from '../content/game-data.json';
export type Language = 'zh-TW' | 'en';
const contentText: Record<string, string[]> = gameData.texts;
const text: Record<string, [string, string]> = {
  ground: ['地面聚落', 'Ground settlement'], overview: ['聚落', 'Settlement'], species: ['物種', 'Species'], workers: ['工作派遣', 'Assignments'], buildings: ['建設', 'Construction'], science: ['研究', 'Research'], records: ['紀錄', 'Records'], achievements: ['成就', 'Achievements'], legacy: ['傳承', 'Legacy'], settings: ['設定與存檔', 'Settings & save'],
  wood: ['木頭', 'Wood'], stone: ['石頭', 'Stone'], food: ['食物', 'Food'], planks: ['木板', 'Planks'], knowledge: ['知識', 'Knowledge'],
  base: ['未分化物種', 'Undifferentiated species'], forest: ['林地型', 'Woodland form'], symbiosis: ['共生型', 'Symbiotic form'], mineral: ['礦質物種', 'Mineral species'],
  workwood: ['伐木', 'Woodcutting'], workstone: ['採石', 'Mining'], workfood: ['採集食物', 'Foraging'], workbuild: ['建造', 'Building'], workcraft: ['加工', 'Crafting'], workresearch: ['研究', 'Research'],
  habitat: ['礦質棲地', 'Mineral habitat'], lumberyard: ['伐木設施', 'Lumberyard'], warehouse: ['倉庫', 'Warehouse'], laboratory: ['研究站', 'Research station'], workshop: ['工坊', 'Workshop'], monument: ['文明傳承碑', 'Legacy monument'], expansion1: ['聚落擴建 I', 'Settlement expansion I'], expansion2: ['聚落擴建 II', 'Settlement expansion II'], camp: ['營地擴充', 'Camp extension'], mineralHabitat: ['第二礦質棲地', 'Second mineral habitat'], recruit: ['招募基礎單位', 'Recruit a base worker'], crafting: ['工藝研究', 'Crafting research'], planning: ['聚落規劃', 'Settlement planning'],
  habitatDesc: ['礦質棲地 +2, 開放物種分歧', '+2 mineral habitat spaces, unlocks evolution'],
  lumberyardDesc: ['2 名伐木者產率 +20%, 每隻限一次加成', '+20% output for 2 woodcutters, once per worker'],
  warehouseDesc: ['所有資源容量 +800', '+800 capacity per resource'],
  laboratoryDesc: ['研究名額 +2, 基礎產率每隻 0.25 知識 / 秒', '+2 research slots, base 0.25 knowledge / worker / s'],
  workshopDesc: ['加工名額 +1, 建造佇列 +1, 每木板消耗 5 木頭', '+1 crafting slot, +1 queue slot, 5 wood / plank'],
  monumentDesc: ['開放傳承, 本輪收益 +10', 'Unlocks Reset, +10 legacy this run'],
  expansion1Desc: ['本輪傳承收益增加 5', 'Adds 5 legacy to this run'], expansion2Desc: ['本輪傳承收益再增加 5', 'Adds another 5 legacy to this run'],
  campDesc: ['基礎棲地 +2', '+2 base habitat spaces'], mineralHabitatDesc: ['礦質棲地 +2', '+2 mineral habitat spaces'], recruitDesc: ['新增 1 個基礎單位, 需營地空位', 'Adds 1 base worker; requires a free camp space'],
  craftingDesc: ['解鎖工坊與木板產線', 'Unlocks the workshop and plank production'], planningDesc: ['解鎖文明傳承碑, 建造佇列容量 +2', 'Unlocks the legacy monument and adds 2 construction queue slots'],
  tools: ['基礎工具', 'Basic tools'], startChoice: ['起始型態選擇', 'Starting form choice'], templates: ['工作配置模板', 'Work templates'],
  toolsDesc: ['每級伐木與採石 +5%, 最多 5 級', '+5% wood and stone per level, up to 5 levels'], startChoiceDesc: ['新一輪可從已發現型態起步', 'Start a new run in a discovered form'], templatesDesc: ['儲存並手動套用配置, 新到的單位可補入空位', 'Save and apply a work plan; new arrivals can fill available slots'],
  population: ['物種總數', 'Workers'], run: ['第 {n} 輪', 'Run {n}'],
  branchTitle: ['物種分歧', 'Species evolution'], branchHelp: ['每輪限選一次', 'One choice per run'],
  forestDesc: ['伐木適性 +50%', '+50% woodcutting aptitude'], symbiosisDesc: ['採集食物適性 +50%', '+50% foraging aptitude'], choose: ['選擇', 'Choose'],
  status: ['生產狀態', 'Production status'], starving: ['食物不足: 基礎物種效率降至 50%, 採集食物不受此影響', 'Food shortage: base efficiency 50%; foraging stays normal'],
  foodBalance: ['採集食物 {made} / 秒, 維持需求 {need} / 秒', 'Foraging {made} / s, upkeep {need} / s'],
  build: ['建造', 'Build'], paused: ['已暫停', 'Paused'], pause: ['暫停', 'Pause'], resume: ['繼續', 'Resume'], cancel: ['取消並返還材料', 'Cancel & return materials'], activeBuild: ['正在建造', 'Construction in progress'], waitingBuild: ['尚未開工', 'No active construction'], noBuilders: ['缺少建造者, 請到工作派遣指派', 'No builders; assign them in Assignments'], workUnit: ['工作量', 'work'], remaining: ['預估剩餘', 'Estimated remaining'],
  busy: ['已有建造項目', 'Construction slot occupied'], locked: ['尚未解鎖', 'Locked'], completed: ['已完成', 'Completed'], materials: ['材料不足', 'Not enough resources'], habitatFull: ['棲地已滿', 'Habitat full'],
  requirement: ['需要: {item}', 'Requires: {item}'], progress: ['進度', 'Progress'],
  refundTitle: ['待領回材料', 'Reserved materials'], refundHelp: ['返還時超出儲存容量的材料會保留在此, 騰出空間後即可領回', 'Refunds beyond capacity stay here. Claim them after making room.'], claim: ['領回材料', 'Claim resources'],
  idle: ['閒置', 'Idle'], baseUpkeep: ['每隻消耗 0.05 食物 / 秒, 含閒置', '0.05 food / worker / s, including idle'], mineralUpkeep: ['不消耗食物, 較耐惡劣天氣', 'No food upkeep, weather resistant'],
  addWorker: ['增加 {species} 的 {job} 數量', 'Add a {species} worker to {job}'], removeWorker: ['減少 {species} 的 {job} 數量', 'Remove a {species} worker from {job}'], unsupported: ['不支援此工作', 'Work not supported'], slotsFull: ['工作名額已滿', 'Work slots full'], workersError: ['沒有可用單位', 'No available worker'], invalidAssignment: ['指派數量不合法', 'Invalid assignment'], noTask: ['沒有建造項目', 'No construction project'],
  efficiency: ['適性', 'Aptitude'], slots: ['名額', 'Slots'], noMinerals: ['完成礦質棲地後加入第二物種', 'Complete a mineral habitat to recruit your second species'],
  purchase: ['研究', 'Research'],
  legacyPoints: ['傳承點數', 'Legacy points'], resetCount: ['已完成輪次', 'Completed cycles'], availableReward: ['本輪可領', 'Run reward'], reset: ['領取傳承並重開', 'Claim & restart'], abandon: ['放棄本輪', 'Abandon run'], resetHelp: ['清除本輪資源, 物種, 派遣, 建築, 研究與分歧, 保留傳承點數與升級, 成就, 已發現型態, 工作模板及星球時間', 'Clears run resources, workers, assignments, buildings, research and evolution. Keeps legacy points and upgrades, achievements, discovered forms, work plans and planet time.'],
  resetConfirm: ['確認開啟新一輪', 'Confirm Reset'], abandonConfirm: ['確認放棄本輪', 'Confirm abandoning this run'], abandonHelp: ['本次收益為 0, 保留已有傳承與升級, 重開地面營地', 'This gives 0 reward. Existing legacy and upgrades are kept; restart at the ground camp.'], confirm: ['確認', 'Confirm'], dismiss: ['關閉', 'Dismiss'], newForm: ['下一輪起始型態', 'Next starting form'], buy: ['購買升級', 'Buy upgrade'], level: ['等級 {n} / 5', 'Level {n} / 5'], legacyPointsError: ['傳承不足', 'Not enough legacy'],
  saveTemplate: ['儲存目前配置', 'Save current plan'], applyTemplate: ['套用配置', 'Apply plan'], noTemplate: ['尚未儲存配置', 'No saved plan'],
  language: ['語言', 'Language'],
  saveTitle: ['存檔', 'Save'], save: ['立即存檔', 'Save now'], export: ['匯出存檔', 'Export save'], import: ['匯入存檔', 'Import save'], importHelp: ['選擇檔案或貼上存檔, 匯入會取代目前進度, 請先匯出備份', 'Choose a file or paste a save. Import replaces current progress; export a backup first.'],
  importConfirm: ['匯入並取代進度', 'Import & replace'], recoverBackup: ['還原上一份存檔', 'Restore previous save'], exportRaw: ['匯出原始存檔', 'Export original save'], jsonLabel: ['存檔內容', 'Save contents'], saved: ['已儲存', 'Saved'], notSaved: ['尚未儲存', 'Not saved yet'],
  savingHelp: ['自動儲存於此瀏覽器, 換裝置前請匯出備份', 'Auto-saved in this browser. Export a backup before switching devices.'],
  imported: ['存檔已匯入', 'Save imported'], invalidSave: ['存檔不合法, 原進度已保留', 'Invalid save; existing progress is preserved'], unsupportedSave: ['不支援此存檔版本, 原進度已保留', 'Unsupported save version; existing progress is preserved'], storageError: ['瀏覽器儲存失敗; 請匯出進度; 新一輪尚未成功儲存時不會入帳', 'Browser storage failed. Export your progress. An unsaved Reset is not credited.'],
  damagedSave: ['原存檔無法讀取, 已停止自動覆寫; 請匯出原檔, 還原備份或匯入有效存檔', 'Save unreadable; automatic overwrites stopped. Export the original, restore a backup or import a valid save.'], backupRecovered: ['已從備份恢復, 請檢查進度並匯出備份', 'Recovered from backup. Check progress and export a backup.'], noBackup: ['沒有可用備份', 'No backup available'],
  inactiveTab: ['此分頁待接續', 'Inactive tab'], browserUnsupported: ['此瀏覽器無法啟動遊戲; 請使用新版 Edge, Chrome, Firefox 或 Safari', 'This browser cannot start the game. Use a current Edge, Chrome, Firefox or Safari.'], sessionError: ['遊戲無法載入, 請備份原存檔後重新整理', 'The game could not load. Back up the original save before reloading.'], simulationError: ['遊戲已暫停, 請匯出存檔並回報問題', 'The game has paused. Export your save and report the issue.'], clockBackwards: ['裝置時間早於存檔時間, 本次沒有離線收益', 'Your device clock is earlier than the save time. No offline progress was added.'],
  bankHelp: ['離線 1.5 小時累積 1 小時的 2x 額度, 上限 8 小時, 前景運作時使用, 暫停時不累積或消耗', 'Every 1.5 hours away grants 1 hour at 2x, capped at 8 hours. Credit is used in the foreground. Pausing stops earning and spending.'],
  accelerationRemaining: ['剩餘 {n} 分鐘', '{n} minutes remaining'],
  nativeCivilization: ['原生文明', 'Native civilization'], nativeIntelligence: ['原生智慧物種', 'Native intelligent species'], civilizationDevelopment: ['文明發展', 'Civilization development'],
  nativehumanoid: ['類人族', 'Humanoid species'], nativecarapace: ['甲殼族', 'Carapace species'], nativecrystalline: ['晶質族', 'Crystalline species'], nativemycelial: ['菌絲族', 'Mycelial species'],
  developmentsettlements: ['聚落社會', 'Settlement society'], developmentcityStates: ['城邦社會', 'City-state society'], developmentindustrial: ['工業社會', 'Industrial society'],
  nativeRelationHelp: ['每顆星球預設一種原生智慧物種, 貿易與殖民交涉尚未開放', 'Each planet starts with one native intelligent species. Trade and colony negotiations are not available yet.'],
  buildingQueued: ['已排入佇列', 'Already queued'],
  offlineHelp: ['正式版完成首次快取後可無網路開啟, 更新於舊頁關閉後啟用, 清除網站資料會移除本機存檔與快取', 'After the production version finishes its first cache, it can open offline. Updates activate after older pages close. Clearing site data removes local saves and caches.'],
  region: ['區域', 'Region'], regionhome: ['起始平原', 'Starting plains'], regionupland: ['高地', 'Uplands'], regioncoast: ['沿岸', 'Coast'],
  regionHelp: ['區域環境比較, 目前聚落生產位於起始平原, 切換檢視不會遷移工作單位', 'Compare regional environments. Current production is in the starting plains. Changing this view does not move workers.'],
  journal: ['聚落紀錄', 'Settlement journal'], arrival: ['工作隊抵達地面營地', 'Your workers arrived at the ground camp'], started: ['開始建造 {item}', 'Started {item}'], built: ['完成 {item}', 'Completed {item}'], cancelled: ['取消 {item}, 材料已退還或保留', 'Cancelled {item}; resources refunded or reserved'], evolved: ['基礎物種分歧為 {item}', 'Base species evolved into {item}'], researched: ['完成 {item}', 'Researched {item}'], purchased: ['購入 {item}', 'Purchased {item}'], resetDone: ['文明傳承已入帳, 新一輪開始', 'Legacy credited. A new run begins.'],
  full: ['滿倉', 'Full'], unavailable: ['待解鎖', 'Locked'], craftBlocked: ['加工受木頭供給或木板容量限制', 'Crafting limited by wood supply or plank capacity'], noCraftWorkers: ['工坊需要 1 名加工者', 'The workshop needs a crafter'],
  newSettlement: ['重新建立聚落', 'Restart settlement'],
  version: ['版本', 'Version'], showCompleted: ['顯示已達上限', 'Show maxed'], noAvailableBuildings: ['目前沒有可建造的項目', 'No construction available'], resourcesTitle: ['資源', 'Resources'], colonySummary: ['聚落總覽', 'Colony overview'],
  populationCount: ['{n} / {max} 隻', '{n} / {max} units'], spawn: ['生成 1 隻', 'Generate 1'], spawned: ['生成 1 隻 {item}', 'Generated 1 {item}'],
  planetTitle: ['星球環境', 'Planet environment'], universeTitle: ['宇宙', 'Universe'], universestandard: ['常態宇宙', 'Standard universe'], universedense: ['高重力宇宙', 'Dense universe'], universevolatile: ['動盪宇宙', 'Volatile universe'], planetName: ['星球', 'Planet'], planetDesignation: ['星球 {n}', 'Planet {n}'], rotation: ['自轉週期', 'Rotation period'], orbit: ['公轉週期', 'Orbital period'], planetDays: ['{n} 個當地日', '{n} local days'], season: ['季節', 'Season'], weather: ['天氣', 'Weather'], spring: ['春季', 'Spring'], summer: ['夏季', 'Summer'], autumn: ['秋季', 'Autumn'], winter: ['冬季', 'Winter'], clear: ['晴朗', 'Clear'], rain: ['降雨', 'Rain'], drought: ['乾旱', 'Drought'], storm: ['暴風雨', 'Storm'], frost: ['寒流', 'Cold snap'], daylight: ['白天', 'Day'], night: ['夜晚', 'Night'], calendarDay: ['第 {year} 年 / 第 {day} 日', 'Year {year} / day {day}'],
  outdoorModifiers: ['基礎物種環境倍率', 'Base species environment'], shelteredWork: ['研究與加工不受天氣影響', 'Research and crafting are sheltered'],
  achievementCount: ['已達成 {n} / {max}', '{n} / {max} earned'], noPermanentBonuses: ['達成成就後自動取得永久加成', 'Earn achievements to gain permanent bonuses'], earned: ['已達成', 'Earned'], unearned: ['未達成', 'Not earned'], achievementPending: ['尚未達成條件', 'Conditions not yet met'], seconds: ['秒', 'seconds'], earnedAt: ['達成時間: {time}', 'Earned: {time}'], achievementUnlocked: ['成就達成: {item}', 'Achievement earned: {item}'],
  achievementsettlement: ['落地生根', 'First foundation'], achievementsettlementDesc: ['完成第一座礦質棲地', 'Complete the first mineral habitat'], achievementdiversity: ['各展所長', 'Many strengths'], achievementdiversityDesc: ['生成礦質物種, 聚落擁有兩種物種', 'Generate a mineral species to house two species'], achievementscholar: ['知識之路', 'Path of knowledge'], achievementscholarDesc: ['完成第一項研究', 'Complete your first research'], achievementlegacy: ['文明延續', 'Civilization endures'], achievementlegacyDesc: ['完成一次傳承並開啟新一輪', 'Claim legacy and begin a new cycle'], achievementendurance: ['風雨同舟', 'Weathering the storm'], achievementenduranceDesc: ['派遣單位在暴風雨或寒流期間累計工作 300 秒', 'Keep workers assigned through storms or cold snaps for 300 seconds'],
  exportBeforeUpgrade: ['匯出升級前存檔', 'Export pre-upgrade save'],
  online: ['運作中', 'Running'], loading: ['正在載入營地', 'Loading your camp'], allocation: ['{used} / {total} 已指派', '{used} / {total} assigned'],
  gameSettings: ['遊戲設定', 'Game settings'],
  iconCredits: ['圖示', 'Icons'],
  queueCapacityHelp: ['初始 2 個名額, 包含正在建造的項目; 每座工坊 +1, 聚落規劃 +2, 最多 12 個', 'Starts with 2 slots including active construction; each workshop adds 1 and settlement planning adds 2, up to 12'], queueTimeHelp: ['依目前建造效率估算的施工時間, 等候材料及前項工程的時間另計', 'Construction time at current efficiency; excludes waiting for materials and earlier projects'],
  queueDragHelp: ['拖曳建築名稱調整等候順序; 鍵盤可用 Alt + 上下方向鍵', 'Drag a building name to reorder waiting projects; use Alt + Up or Down with a keyboard'], queueDrag: ['拖曳排序 {item}', 'Drag to reorder {item}'],
  subtabs: ['內容分類', 'Content sections'], summary: ['總覽', 'Overview'], environmentDetails: ['環境詳情', 'Environment details'], availableResearch: ['可研究科技', 'Available technologies'], completedResearch: ['已完成研究', 'Completed research'], milestoneTab: ['發展進度', 'Milestones'], journalTab: ['聚落紀錄', 'Journal'], achievementList: ['成就列表', 'Achievements'], permanentBonuses: ['永久加成', 'Permanent bonuses'], legacyOverview: ['文明傳承', 'Civilization legacy'],
  buildingCount: ['已建 {n} 座', '{n} built'], uniqueBuilding: ['限建 1 座', 'Limit 1'], plannedCount: ['已排入 {n} 座', '{n} planned'], buildingLimit: ['已達建造上限', 'Building limit reached'], addToQueue: ['排入佇列', 'Queue'], queueFull: ['建造佇列已滿', 'Queue full'], invalidQueue: ['此建造項目已變動', 'This queue entry has changed'], buildQueue: ['建造佇列', 'Construction queue'], queuePaused: ['佇列已暫停, 正在建造的項目會繼續', 'Queue paused; active construction continues'], queueWaiting: ['依序接續, 開工時消耗材料', 'Continues in order; materials are consumed at start'], queueNeedsMaterials: ['等待材料足夠後自動開工', 'Starts automatically when materials are ready'], queueNeedsStorage: ['材料需求超出容量, 請先擴充倉庫', 'Cost exceeds capacity; expand storage first'], pauseQueue: ['暫停佇列', 'Pause queue'], resumeQueue: ['繼續佇列', 'Resume queue'], queueMoveUp: ['將 {item} 往前移', 'Move {item} earlier'], queueMoveDown: ['將 {item} 往後移', 'Move {item} later'], queueRemove: ['移除 {item}', 'Remove {item}'], queued: ['{item} 已加入建造佇列', '{item} added to construction queue'], queueRemoved: ['{item} 已從建造佇列移除', '{item} removed from construction queue'],
  forestry: ['林地經營', 'Woodland management'], forestryDesc: ['伐木產率 +10%, 解鎖培育林地', '+10% wood output, unlocks cultivated groves'], cultivation: ['生態栽培', 'Ecological cultivation'], cultivationDesc: ['採集食物產率 +10%, 開放生命調和研究', '+10% food output, unlocks vitality research'], mineralogy: ['礦質共振', 'Mineral resonance'], mineralogyDesc: ['礦質物種採石產率 +15%, 解鎖共振採石場', '+15% mineral-species stone output, unlocks resonance quarries'], arcana: ['魔力運用', 'Arcane application'], arcanaDesc: ['魔法之風提升研究產率, 解鎖魔力共鳴塔', 'Magic winds improve research output, unlocks resonators'], vitality: ['生命調和', 'Vital harmonization'], vitalityDesc: ['戶外採集與建造效率 +8%', '+8% outdoor gathering and construction'],
  grove: ['培育林地', 'Cultivated grove'], groveDesc: ['伐木產率 +5%', '+5% wood output'], quarry: ['共振採石場', 'Resonance quarry'], quarryDesc: ['礦質物種採石產率 +5%', '+5% mineral-species stone output'], resonator: ['魔力共鳴塔', 'Arcane resonator'], resonatorDesc: ['提升魔力研究增益, 隨星球魔力與物種親和性變動', 'Boosts arcane research by planet magic and species affinity'],
  mineralCondition: ['礦質物種至少 {n} 隻', 'At least {n} mineral workers'], moistureCondition: ['水分係數至少 {n}%', 'Moisture at least {n}%'], arcaneCondition: ['魔力潛能至少 {n}%', 'Arcane potential at least {n}%'], vitalityCondition: ['生命脈動至少 {n}%', 'Vitality field at least {n}%'], noCompletedResearch: ['尚未完成研究', 'No completed research'], noAvailableResearch: ['目前沒有新的可研究科技', 'No new technologies available'],
  gravity: ['相對重力', 'Relative gravity'], moisture: ['水分係數', 'Moisture'], arcanePotential: ['魔力潛能', 'Arcane potential'], vitalityField: ['生命脈動', 'Vitality field'], magicWind: ['魔法之風', 'Magic winds'], magicWindPulse: ['魔力潮汐', 'Arcane tide'], magicAffinity: ['魔力親和性', 'Magic affinity'], vitalityAffinity: ['生命親和性', 'Vitality affinity'],
  bonussettlement: ['永久加成: 建造效率 +2%', 'Permanent: +2% construction'], bonusdiversity: ['永久加成: 採石產率 +2%', 'Permanent: +2% stone output'], bonusscholar: ['永久加成: 研究產率 +3%', 'Permanent: +3% research output'], bonuslegacy: ['永久加成: 伐木, 採石與採集食物產率 +2%', 'Permanent: +2% wood, stone and food output'], bonusendurance: ['永久加成: 天氣造成的效率損失減少 10%', 'Permanent: weather efficiency losses reduced by 10%'], earnedDateUnknown: ['舊存檔未記錄達成日期', 'Earned date was not recorded in the older save'], compressionUnsupported: ['此瀏覽器無法解壓縮存檔, 請使用新版瀏覽器或匯入原始存檔', 'This browser cannot decompress saves. Use a current browser or import the original save'],
};
export function translate(language: Language, key: string, values: Record<string, string | number> = {}): string {
  let result = (contentText[key] ?? text[key])?.[language === 'zh-TW' ? 0 : 1] ?? key;
  for (const [name, value] of Object.entries(values)) result = result.replaceAll(`{${name}}`, String(value));
  return result;
}
export function duration(seconds: number): string {
  if (!Number.isFinite(seconds)) return '--:--';
  const value = Math.max(0, Math.ceil(seconds));
  const hours = Math.floor(value / 3600);
  const minutes = Math.floor(value % 3600 / 60);
  const secs = (value % 60).toString().padStart(2, '0');
  return hours ? `${hours}:${minutes.toString().padStart(2, '0')}:${secs}` : `${minutes}:${secs}`;
}
